package com.example.test.commonFuncs;

import com.example.test.R;
public class LevelsInfo {
    public final int requaredAmount = 15;

    public Integer[][] premiaImagesList = {{R.drawable.artist_0_1_mumitrol},  {R.drawable.artist_1_1_pugacheva, R.drawable.artist_1_5_leps, R.drawable.artist_1_4_mihaylov, R.drawable.artist_1_2_timati, R.drawable.artist_1_6_elka, R.drawable.artist_1_7_bilan, R.drawable.artist_1_8_shnur, R.drawable.artist_1_9_gradskiy},  {R.drawable.artist_2_1_pelagya, R.drawable.artist_2_2_chayvdvoem, R.drawable.artist_2_3_nyusha, R.drawable.artist_2_4_shufutinskij, R.drawable.artist_2_5_mashinavremeni, R.drawable.artist_2_6_kirkorov, R.drawable.artist_2_7_maksim, R.drawable.artist_2_8_kasta, R.drawable.artist_2_9_glukoza, R.drawable.artist_2_10_zakirova, R.drawable.artist_2_11_taty, R.drawable.artist_2_12_kino, R.drawable.artist_2_13_baskov, R.drawable.artist_2_14_agutin, R.drawable.artist_2_15_guf, R.drawable.artist_2_16_nikolaev, R.drawable.artist_2_17_boiarskij, R.drawable.artist_2_18_vaenga},
             {R.drawable.artist_3_1_vysockij, R.drawable.artist_3_2_meladze, R.drawable.artist_3_3_splin, R.drawable.artist_3_4_rozenbaum, R.drawable.artist_3_5_basta, R.drawable.artist_3_6_korolishut, R.drawable.artist_3_7_lazarev, R.drawable.artist_3_8_decl, R.drawable.artist_3_9_potapinastia, R.drawable.artist_3_10_rukivverh, R.drawable.artist_3_11_uma2rman, R.drawable.artist_3_12_viagra, R.drawable.artist_3_13_ariya, R.drawable.artist_3_14_lolita, R.drawable.artist_3_15_antonov, R.drawable.artist_3_16_sergey, R.drawable.artist_3_17_gazmanov, R.drawable.artist_3_18_bg},  {R.drawable.artist_4_1_ivanushki, R.drawable.artist_4_2_ddt, R.drawable.artist_4_3_agatakristi, R.drawable.artist_4_4_vitas, R.drawable.artist_4_5_zverev, R.drawable.artist_4_6_gurcheno, R.drawable.artist_4_7_discotekaavariya, R.drawable.artist_4_8_fadeev, R.drawable.artist_4_9_moiseev, R.drawable.artist_4_10_friske, R.drawable.artist_4_11_kobzon, R.drawable.artist_4_12_peha, R.drawable.artist_4_13_lube, R.drawable.artist_4_14_zemfira, R.drawable.artist_4_15_trofim, R.drawable.artist_4_16_sukachev, R.drawable.artist_4_17_penkin, R.drawable.artist_4_18_naiv},
             {R.drawable.artist_5_1_leontiv, R.drawable.artist_5_2_faktor2, R.drawable.artist_5_3_varum, R.drawable.artist_5_4_vitiaak, R.drawable.artist_5_5_brezhneva, R.drawable.artist_5_6_aguzarova, R.drawable.artist_5_7_bratiagrim, R.drawable.artist_5_8_valeria, R.drawable.artist_5_9_koroltva, R.drawable.artist_5_10_piknik, R.drawable.artist_5_11_kadeshiva, R.drawable.artist_5_12_rotary, R.drawable.artist_5_13_ryso, R.drawable.artist_5_14_reflex, R.drawable.artist_5_15_babkina, R.drawable.artist_5_16_serov, R.drawable.artist_5_17_chaif, R.drawable.artist_5_18_raspytina},  {R.drawable.artist_6_1_serduchka, R.drawable.artist_6_2_qest_pistoles, R.drawable.artist_6_3_hifi, R.drawable.artist_6_4_koroziametalla, R.drawable.artist_6_5_dzhigurda, R.drawable.artist_6_6_nana, R.drawable.artist_6_7_shura, R.drawable.artist_6_8_laskoviymaj, R.drawable.artist_6_9_tokarev}, {}};

    public String[][][] correctAnswersList = {{{"мумий тролль"}},
            {{"пугачева", "алла пугачева", "алла борисовна", "алла"}, {"лепс", "лепс григорий", "григорий лепс", "григорий лепсверидзе", "плепс", "лепсверидзе григорий"}, {"стас михайлов", "михайлов", "станислав михайлов", "михайлов станислав"}, {"тимати", "тимур юнусов", "Timati", "тимур сказка", "тимур беноевский", "теймураз"}, {"елка", "елизавета иванцив", "иванцив елизавета", "иванцив лиза", "лиза иванцив", "иванцив"}, {"дима билан", "дима белан", "виктор билан", "виктор белан", "билан дима", "белан дима", "билан виктор", "белан виктор", "билан", "белан"}, {"сергей шнуров", "шнур", "ленинград", "шнуров сергей", "шнуров"}, {"градский", "александр градский", "градский александр", "александр фрадкин", "фрадкин александр", "славяне", "скоморохи"}},
            {{"пелагея", "телегина", "пелагея телегина", "телегина пелагея", "смирнова полина", "полина смирнова"}, {"чай вдвоем"}, {"нюша"}, {"шуфутинский", "михаил шуфутинский", "шуфутинский михаил", "миша", "михаил"}, {"машина времени", "макаревич", "андрей макаревич", "макаревич андрей"}, {"филипп киркоров", "киркоров филипп", "филипп бедросович", "бедросович филипп", "филипп", "бедросович", "киркоров"}, {"максим"}, {"каста"}, {"глюкоза"}, {"наргиз", "закирова", "наргиз закирова", "закирова наргиз"}, {"тату"}, {"кино", "Цой", "виктор Цой", "Цой виктор"}, {"басков", "николай басков", "басков николай"}, {"агутин", "леонид агутин", "агутин леонид"}, {"гуф"}, {"николаев", "игорь николаев", "николаев игорь"}, {"боярский", "михаил боярский", "боярский михаил"}, {"ваенга"}},
            {{"высоцкий", "владимир высоцкий", "высоцкий владимир"}, {"меладзе", "константин меладзе", "меладзе константин"}, {"сплин", "васильев", "александр васильев", "васильев александр"}, {"розенбаум"}, {"баста", "вася", "василий", "наггано", "василий вакуленко", "вакуленко"}, {"король и шут", "киш", "горшок", "князь", "князев", "горшенев"}, {"сергей лазарев", "лазарев сергей", "лазарев"}, {"децл", "кирилл толмацкий", "толмацкий кирилл", "толмацкий"}, {"потап и настя", "настя и потап", "потап", "потап и настя каменских"}, {"руки вверх", "жуков", "сергей жуков", "жуков сергей"}, {"уматурман", "ума2рман"}, {"виагра"}, {"ария", "кипелов"}, {"лолита", "милявская", "милявская лолита", "милявская"}, {"антонов"}, {"серега", "серёга"}, {"газманов", "олег газманов", "газманов олег"}, {"гребенщиков", "борис гребенщиков", "бг"}},
            {{"иванушки"}, {"ддт", "юрий шевчук", "шевчук юрий", "шевчук"}, {"агата кристи", "самойловы", "самойлов", "братья самойловы"}, {"витас"}, {"зверев", "сергей зверев", "зверев сергей"}, {"гурченко", "людмила гурченко", "гурченко людмила"}, {"дискотека авария"}, {"фадеев", "максим фадеев", "фадеев максим"}, {"моисеев", "борис моисеев", "моисеев борис"}, {"фриске", "жанна фриске", "фриске жанна"}, {"кобзон", "иосиф кобзон", "кобзон иосиф"}, {"эдита пьеха", "пьеха", "пьеха эдита"}, {"любэ", "расторгуев", "николай расторгуев", "расторгуев николай"}, {"земфира"}, {"трофим", "сергей трофимов", "трофимов сергей"}, {"сукачев", "гарик сукачев", "сукачев гарик", "неприкосаемые"}, {"пенкин", "сергей пенкин", "пенкин сергей"}, {"наив"}},
            {{"леонтьев"}, {"фактор 2", "фактор два", "фактор2"}, {"варум", "анжелика варум", "варум анжелика"}, {"витя ак", "витяак", "витя", "ак-47", "ак", "ак 47"}, {"вера брежнева", "брежнева", "брежнева вера"}, {"агузарова", "жанна агузарова", "агузарова жанна"}, {"братья грим", "грим"}, {"валерия", "валерия перфилова", "перфилова валерия"}, {"королева", "королёва", "наташа королева", "наташа королёва", "наталия королева", "наталья королева", "наталья королёва", "наталия королёва"}, {"пикник", "эдмунд шклярский", "шклярский", "шклярский эдмунд"}, {"кадышева", "надежда кадышева", "кадышева надежда"}, {"софия ротару", "ротару", "ротару софия"}, {"авраам руссо", "руссо", "авраам", "руссо авраам"}, {"рефлекс"}, {"бабкина", "надежда бабкина", "бабкина надежда"}, {"серов"}, {"чайф"}, {"распутина", "маша распутина", "распутина маша"}},
            {{"сердючка", "верка сердючка", "сердючка верка"}, {"quest pistols", "квестпистолс", "квест пистолс"}, {"Hi-Fi", "хайфай", "хай фай", "хай-фай", "hi fi"}, {"коррозия металла", "паук"}, {"джигурда"}, {"нана"}, {"шура"}, {"ласковый май", "юрий шатунов", "шатунов", "шатунов юра"}, {"токарев", "вилли токарев", "токарев вилли"}},
            {{""}}};

    public String[][] albomsList = {{"Альбом: Морская\nПесня: Владивосток 2000"},
            {"Альбом: Да!\nПесня: Позови меня с собой", "Альбом: На струнах дождя...\nПесня: Рюмка водки на столе", "Альбом: Берега мечты\nПесня: Всё для тебя", "Альбом: Black Star\nПесня: В Клубе", "Альбом: Точки расставлены\nПесня: Прованс", "Альбом: Я ночной хулиган\nПесня: Я ночной хулиган", "Альбом: Для миллионов\nПесня: Менеджер", "Альбом: ЖИВьЁМ в России\nПесня: Как молоды мы были..."},
            {"Альбом: Девушкины песни\nПесня: Казак", "Альбом: Ласковая моя\nПесня: Ласковая моя", "Альбом: Объединение\nПесня: Наедине", "Альбом: Гуляй, душа\nПесня: Третье сентября", "Альбом: В круге света\nПесня: Герои вчерашних дней", "Альбом: Незнакомка\nПесня: Роза чайная", "Альбом: Трудный возраст\nПесня: Знаешь ли ты", "Альбом: Громче воды, выше травы\nПесня: Куда надо смотреть", "Альбом: Москва\nПесня: Снег идёт", "Альбом: Шум сердца\nПесня: Ты - моя нежность", "Альбом: 200 по встречной\nПесня: Я сошла с ума", "Альбом: 45\nПесня: Восьмиклассница", "Альбом: Посвящение\nПесня: Памяти Карузо", "Альбом: Босоногий мальчик\nПесня: Хоп Хэй Лала Лэй", "Альбом: Город до́рог\nПесня: Сплетни", "Альбом: Дельфин и русалка\nПесня: Такси, такси", "Альбом: Графский переулок\nПесня: Петербург моего одиночества", "Альбом: Клавиши\nПесня: Курю"},
            {"Альбом: Концерт в ДК Мир\nПесня: Песня о друге", "Альбом: Самба белого мотылька\nПесня: Самба белого мотылька", "Альбом: 25-й кадр\nПесня: Моё сердце", "Альбом: Мои дворы\nПесня: Вальс-бостон", "Альбом: 3\nПесня: Солнца не видно", "Альбом: Как в старой сказке \nПесня: Проклятый старый дом", "Альбом: The best\nПесня: В самое сердце", "Альбом: Кто? Ты\nПесня: Вечеринка ", "Альбом: Не пара\nПесня: Не пара ", "Альбом: Без тормозов\nПесня: Ну, где же вы девчонки?", "Альбом: В городе N\nПесня: Проститься", "Альбом: Попытка № 5\nПесня: Что же я наделала?", "Альбом: Крещение огнём\nПесня: Колизей", "Альбом: Фетиш\nПесня: Прощай, оружие!", "Альбом: Крыша дома твоего\nПесня: Крыша дома твоего", "Альбом: The best of...\nПесня: Чёрный бумер", "Альбом: Морячка\nПесня: Морячка", "Альбом: Беспечный русский бродяяга\nПесня: Стаканы"},
            {"Альбом: Твои письма\nПесня: Кукла", "Альбом: Актриса Весна\nПесня: Родина", "Альбом: Ураган\nПесня: Грязь", "Альбом: Философия чуда\nПесня: Опера 2", "Альбом: Ради тебя\nПесня: Алла", "Альбом: -\nПесня: 5 минут", "Альбом: Авария против!\nПесня: Пей Пиво!", "Альбом: Ножницы\nПесня: Танцы на стеклах", "Альбом: Праздник! Праздник!\nПесня: Голубая луна", "Альбом: Жанна\nПесня: Ла-ла-ла", "Альбом: Танго, Танго, Танго\nПесня: Счастье Мое", "Альбом: -\nПесня: Наш сосед", "Альбом: Песни о людях\nПесня: Там, за туманами", "Альбом: Прости меня моя любовь\nПесня: Хочешь", "Альбом: Ветер в голове\nПесня: Боже, какой пустяк", "Альбом: Ночной полёт\nПесня: Моя бабушка курит трубку", "Альбом: Мистер Икс\nПесня: Ария Мистера Икс", "Альбом: Форева\nПесня: Я не шучу"},
            {"Альбом: Муза\nПесня: Полет на дельтаплане", "Альбом: В нашем стиле\nПесня: Красавица", "Альбом: Ля-ля-фа\nПесня: Ля-ля-фа", "Альбом: МегаPolice\nПесня: Оля Лукина", "Альбом: Любовь спасёт мир\nПесня: Любовь спасёт мир", "Альбом: Bravo\nПесня: Кошки", "Альбом: Братья Грим\nПесня: Ресницы", "Альбом: Страна Любви\nПесня: Часики", "Альбом: Конфетти\nПесня: Маленькая страна", "Альбом: Королевство кривых\nПесня: У шамана три руки", "Альбом: Когда-нибудь\nПесня: Широка река", "Альбом: Я: твоя любовь!\nПесня: Я назову планету", "Альбом: Обручальная\nПесня: Обручальная", "Альбом: Пульс\nПесня: Танцы", "Альбом: Продлись, моё счастье\nПесня: Финская полька", "Альбом: Я люблю тебя до слёз\nПесня: Я люблю тебя до слёз", "Альбом: Время не ждёт\nПесня: Не доводи до предела", "Альбом: Городская Сумасшедшая\nПесня: Клава"},
            {"Альбом: Ха-Ра-Шо!\nПесня: Все будет хорошо", "Альбом: Для тебя\nПесня: Я устал", "Альбом: Первый контакт\nПесня: Ты прости", "Альбом: Орден Сатаны\nПесня: Фантом", "Альбом: Волчья кровь\nПесня: Огонь любви", "Альбом: Фаина\nПесня: Фаина", "Альбом: Благодарю. Второе дыхание\nПесня: Твори добро", "Альбом: Белые розы\nПесня: Седая ночь", "Альбом: Над гудзоном\nПесня: Рыбацкая"},
            {""}};

    public Integer premiasAmount = 8;

    public Integer getLevelsAmount() {
        int amount = 0;
        for (int i = 1; i < premiaImagesList.length - 1; i++) {
            amount += premiaImagesList[i].length;
        }
        return amount;
    }

        public Integer[][] premiaDisksList = {{R.drawable.obychenie_0, R.drawable.obychenie_1}, {R.drawable.lvl11, R.drawable.lvl12, R.drawable.lvl13, R.drawable.lvl14, R.drawable.lvl15, R.drawable.lvl16, R.drawable.lvl17, R.drawable.lvl18, R.drawable.lvl19}, {R.drawable.lvl21, R.drawable.lvl22, R.drawable.lvl23, R.drawable.lvl24, R.drawable.lvl25, R.drawable.lvl26, R.drawable.lvl27, R.drawable.lvl28, R.drawable.lvl29, R.drawable.lvl210, R.drawable.lvl211, R.drawable.lvl212, R.drawable.lvl213, R.drawable.lvl214, R.drawable.lvl215, R.drawable.lvl216, R.drawable.lvl217, R.drawable.lvl218, R.drawable.lvl219}, {R.drawable.lvl31, R.drawable.lvl32, R.drawable.lvl32, R.drawable.lvl33, R.drawable.lvl34, R.drawable.lvl35, R.drawable.lvl36, R.drawable.lvl37, R.drawable.lvl38, R.drawable.lvl39, R.drawable.lvl311, R.drawable.lvl312, R.drawable.lvl313, R.drawable.lvl314, R.drawable.lvl315, R.drawable.lvl316, R.drawable.lvl317, R.drawable.lvl318, R.drawable.lvl319}, {R.drawable.lvl41, R.drawable.lvl42, R.drawable.lvl42, R.drawable.lvl43, R.drawable.lvl44, R.drawable.lvl45, R.drawable.lvl46, R.drawable.lvl47, R.drawable.lvl48, R.drawable.lvl49, R.drawable.lvl411, R.drawable.lvl412, R.drawable.lvl413, R.drawable.lvl414, R.drawable.lvl415, R.drawable.lvl416, R.drawable.lvl417, R.drawable.lvl418, R.drawable.lvl419}, {R.drawable.lvl51, R.drawable.lvl52, R.drawable.lvl52, R.drawable.lvl53, R.drawable.lvl54, R.drawable.lvl55, R.drawable.lvl56, R.drawable.lvl57, R.drawable.lvl58, R.drawable.lvl59, R.drawable.lvl511, R.drawable.lvl512, R.drawable.lvl513, R.drawable.lvl514, R.drawable.lvl515, R.drawable.lvl516, R.drawable.lvl517, R.drawable.lvl518, R.drawable.lvl519}, {R.drawable.lvl61, R.drawable.lvl62, R.drawable.lvl62, R.drawable.lvl63, R.drawable.lvl64, R.drawable.lvl65, R.drawable.lvl66, R.drawable.lvl67, R.drawable.lvl68, R.drawable.lvl69}, {R.drawable.lvl70}};
        public Integer[] premiaDisksListClosed = {R.drawable.obychenie_0, R.drawable.lvl11, R.drawable.lvl20, R.drawable.lvl30, R.drawable.lvl40, R.drawable.lvl50, R.drawable.lvl60, R.drawable.lvl70};




    }


